#!/bin/bash
#SignApp Install script v1.5
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
cd "$DIR"
curl --silent -LJO https://raw.githubusercontent.com/Diatrus/SignApp/master/Resources/SignApp > SignApp
sudo mv "SignApp" "/usr/local/bin/SignApp" 
sudo chmod 0755 /usr/local/bin/SignApp
echo "Success! SignApp can now be run anywhere!"
echo "Run this script again anytime to update SignApp."
